# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a54cc383121830645721e05635832da36ce7190b6ff9ad0a5f183de5b30e5511d8e019c4814cb52c2afdabccc2ad13a9c5d8a68d386029d1c29891098bc994b

test:
  secret_key_base: 76c4bcea2e5dffeca861a5d5e2938d670753a826e247cd2f537bad13caa80ea6c4d2073b84125f99902023c5bdce5346288a67099f60cf8d179eacae4757dc2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
